### ISSUE TITLE
Unable to trigger event

### ISSUE THREAD

**Issue by spongeBri** [apardo04/locust-github-action#6]
Running this locally i am able to trigger the event and fail the test on the results of the avg response.

But running it via github actions i get the following

``` bash
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 POST xapi-statement                                             4375     0(0.00%)     158     132     712  |     150   39.20    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                      4375     0(0.00%)     158     132     712  |     150   39.20    0.00

[2023-10-27 10:09:36,337] 39ea71187fac/INFO/locust.main: Time limit reached. Stopping Locust.
[2023-10-27 10:09:36,356] 39ea71187fac/INFO/locust.main: Shutting down (exit code 0), bye.
[2023-10-27 10:09:36,356] 39ea71187fac/INFO/locust.main: Cleaning up runner...
[2023-10-27 10:09:36,356] 39ea71187fac/INFO/locust.main: Running teardowns...
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/locust/main.py", line 324, in main
    shutdown(code=code)
  File "/usr/local/lib/python3.8/site-packages/locust/main.py", line 302, in shutdown
    environment.events.quitting.fire(reverse=True)
  File "/usr/local/lib/python3.8/site-packages/locust/event.py", line 33, in fire
    handler(**kwargs)
TypeError: _() missing 1 required positional argument: 'environment'
```

I have added a event logger with

``` python
import logging
from locust import events


class logger:
    @events.quitting.add_listener
    def _(environment):
        if environment.stats.total.fail_ratio > 25:
            logging.error("Test failed due to failure ratio > 25%")
            environment.process_exit_code = 1
        elif environment.stats.total.avg_response_time > 5:
            logging.error(
                "Test failed due to average response time ratio > 5 ms")
            environment.process_exit_code = 1
        else:
            environment.process_exit_code = 0
```

This is added into the test class

``` python
from lib.locust_logger import logger

class Trainee(HttpUser, logger):
    wait_time: int = between(1, 5)
    response_time: int = 5
    ....
```

I am not sure what's preventing the locust environment being passed to the event listener

**Comment by spongeBri** [comment]
This is due to the default version of locust being 1.0.1, so you need to add a newer version in your requirements.txt.

**Comment by apardo04** [comment]
Hey, just got to this. What version of locust ended up working for you?
Seems I would have to update this line: https://github.com/apardo04/locust-github-action/blob/master/Dockerfile#L3
